/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'security',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'web',
        'gateway',
        'course',
        'assessment',
        'certificate',
        'ranking',
        'rag',
        'notification',
        'shared',
        'ui',
        'infra',
        'supabase',
        'docs',
        'ci',
        'deps',
      ],
    ],
    'subject-case': [2, 'never', ['pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
